# Auto-generated by deploy-aws.sh from tfvars state_*/region variables.
# Do not edit manually — update the tfvars file instead.

bucket       = "tiberio-tfstate-v2"
key          = "terraform.tfstate"
region       = "eu-west-1"
encrypt      = true
use_lockfile = true
